export const safetyGuides = [
  {
    id: "train",
    icon: "🚇",
    title: "Train Harassment",
    subtitle: "Someone is touching, blocking, or following you on the train.",
    phrase: "やめてください！",
    steps: [
      ["First Step", "Move toward a crowded area, the door, or another carriage as soon as you can."],
      ["Say it loudly", "Use a clear, direct phrase. You do not need to be polite when you are unsafe."],
      ["Ask for help", "Tell a station staff member, nearby passenger, or police officer what happened."],
      ["Save evidence", "Record the time, train line, carriage number, station, and any details you remember."],
    ],
  },
  {
    id: "followed",
    icon: "🚶",
    title: "Being Followed",
    subtitle: "You feel someone is repeatedly following your route.",
    phrase: "ついてこないでください。",
    steps: [
      ["First Step", "Do not go home. Turn toward a bright store, station gate, police box, or busy street."],
      ["Check safely", "Change direction once and notice if the person mirrors you. Do not confront alone."],
      ["Ask for help", "Enter a convenience store or cafe and tell staff: someone may be following me."],
      ["Share location", "Send your current location to an emergency contact and keep your phone visible."],
    ],
  },
  {
    id: "night",
    icon: "🌃",
    title: "Walking Home",
    subtitle: "You are going home late and want a safer route.",
    phrase: "近くまで一緒にいてもらえますか？",
    steps: [
      ["First Step", "Choose lit streets, stations, convenience stores, and roads with people nearby."],
      ["Stay connected", "Start a fake call or real call before leaving the station or building."],
      ["Avoid shortcuts", "Skip quiet parks, underpasses, empty alleys, and stairways even if they are faster."],
      ["Prepare arrival", "Have keys ready before the door and look around before entering your building."],
    ],
  },
  {
    id: "door",
    icon: "🏠",
    title: "Stranger at Door",
    subtitle: "Someone is ringing or knocking and you are not expecting anyone.",
    phrase: "どちら様ですか？用件を教えてください。",
    steps: [
      ["First Step", "Keep the door locked. Do not open the door chain or confirm that you are alone."],
      ["Ask clearly", "Ask for name, company, and purpose through the door or intercom."],
      ["Verify", "If they claim delivery, building staff, or utility work, check through official contact channels."],
      ["Escalate", "If they do not leave, call building management, a nearby contact, or police."],
    ],
  },
  {
    id: "ride",
    icon: "🚕",
    title: "Unsafe Ride",
    subtitle: "A taxi or rideshare route or driver behavior feels wrong.",
    phrase: "ここで降ります。",
    steps: [
      ["First Step", "Share your live location and keep the route open on your own map."],
      ["Create friction", "Call someone and state the car plate, driver name, and route out loud."],
      ["Exit safely", "Ask to stop at a bright convenience store, station, hotel, or busy crossing."],
      ["Report", "Save receipt, plate, time, and route. Report the driver through the service or police."],
    ],
  },
  {
    id: "emergency",
    icon: "🆘",
    title: "Emergency",
    subtitle: "You need immediate help or cannot safely leave.",
    phrase: "助けてください！警察を呼んでください！",
    steps: [
      ["First Step", "Call 110 for police in Japan. If injured or in medical danger, call 119."],
      ["Make yourself visible", "Move toward light, people, cameras, or an open business if possible."],
      ["Use short words", "Say where you are, what is happening, and what you need right now."],
      ["Do not delay", "If you feel in immediate danger, use emergency services before app features."],
    ],
  },
];

export const callers = [
  {
    id: "mom",
    name: "Mom",
    avatar: "M",
    role: "Warm and direct",
    lines: ["Are you there?", "I am nearby now.", "Can you come outside?", "Stay on the phone with me."],
  },
  {
    id: "friend",
    name: "Mina",
    avatar: "M",
    role: "Close friend",
    lines: ["Hey, I can see your location.", "I am walking toward you.", "Keep talking to me.", "Let's meet at the entrance."],
  },
  {
    id: "roommate",
    name: "Roommate",
    avatar: "R",
    role: "At home",
    lines: ["I am waiting downstairs.", "Do you want me to call you?", "Don't come up alone.", "Send me the building entrance."],
  },
  {
    id: "boss",
    name: "Boss",
    avatar: "B",
    role: "Formal excuse",
    lines: ["Can you join the call now?", "We need you back online.", "Please step out and call me.", "I will stay connected."],
  },
];

export const livingGuides = [
  {
    id: "washing-machine-drain",
    category: "Home Basics",
    title: "Washing Machine Won’t Drain",
    summary: "A calm check for standing water, lint filters, and when to stop before touching appliance parts.",
    keywords: ["washing machine", "laundry", "drain", "water", "appliance"],
    riskLevel: "Medium",
    risk: "Medium",
    time: "15 min",
    diy: "Limited",
    beforeYouStart: ["Turn the machine off.", "Keep your hands dry around the outlet.", "Place towels near the machine if water is visible."],
    tools: ["Towels", "Small bowl", "Flashlight", "Manual if available"],
    problem: "The washing machine has water inside or will not complete the drain cycle.",
    steps: ["Pause the machine and unplug it only if the plug area is dry and easy to reach.", "Check whether the drain hose is bent or pressed behind the machine.", "Look for a visible lint filter panel and follow the machine manual only if it is easy to open.", "Take a photo of any error code before contacting support."],
    stopAndAskForHelp: "Stop and contact your landlord, building management, utility company, or emergency service if water reaches an outlet, you smell burning, the machine sparks, or there is major water leakage.",
    warning: "Stop and contact your landlord, building management, utility company, or emergency service if water reaches an outlet, you smell burning, the machine sparks, or there is major water leakage.",
    japanesePhrases: ["洗濯機の水が排水されません。", "エラーコードが出ています。", "修理をお願いできますか？"],
    phrases: ["洗濯機の水が排水されません。", "エラーコードが出ています。", "修理をお願いできますか？"],
  },
  {
    id: "utilities-setup",
    category: "Money & Budget",
    title: "How to Set Up Utilities",
    summary: "A first-apartment checklist for electricity, gas, water, internet, and safe contact points.",
    keywords: ["utilities", "electricity", "gas", "water", "internet", "set up", "moving"],
    riskLevel: "Medium",
    risk: "Medium",
    time: "30 min",
    diy: "Admin only",
    beforeYouStart: ["Prepare your address, move-in date, phone number, and residence card if needed.", "Ask your landlord which providers serve the building.", "Do not open gas valves or electrical panels yourself."],
    tools: ["Rental contract", "Phone", "Provider website", "Move-in date"],
    problem: "You need to start basic home services without missing a safety step.",
    steps: ["Confirm which utilities are already connected by the building.", "Apply for electricity and water using official provider forms.", "Book a gas opening appointment if gas is used in the room.", "Save emergency phone numbers for electricity, gas, and building management."],
    stopAndAskForHelp: "Stop and contact your landlord, building management, utility company, or emergency service for gas opening, electrical faults, gas smell, damaged meters, or unclear utility equipment.",
    warning: "Stop and contact your landlord, building management, utility company, or emergency service for gas opening, electrical faults, gas smell, damaged meters, or unclear utility equipment.",
    japanesePhrases: ["電気・ガス・水道の開始手続きをしたいです。", "ガスの開栓予約をお願いします。", "管理会社に確認します。"],
    phrases: ["電気・ガス・水道の開始手続きをしたいです。", "ガスの開栓予約をお願いします。", "管理会社に確認します。"],
  },
  {
    id: "toilet-clogged",
    category: "Home Basics",
    title: "Toilet Is Clogged",
    summary: "Simple first steps for a clogged toilet, with clear stop points for overflow or leakage.",
    keywords: ["toilet", "clogged", "bathroom", "water", "plunger"],
    riskLevel: "Medium",
    risk: "Medium",
    time: "15 min",
    diy: "Limited",
    beforeYouStart: ["Do not flush repeatedly.", "Put towels on the floor.", "Keep cleaning products separate and never mix chemicals."],
    tools: ["Rubber gloves", "Plunger", "Towels", "Trash bag"],
    problem: "The toilet water is rising, draining slowly, or not clearing after one flush.",
    steps: ["Stop flushing and wait for the water level to settle.", "Use a plunger gently with enough water to cover the rubber cup.", "Try several slow pushes rather than forceful splashing.", "Clean the area and wash your hands thoroughly if the water clears."],
    stopAndAskForHelp: "Stop and contact your landlord, building management, utility company, or emergency service if water overflows, the floor leaks, sewage smell spreads, or the clog does not clear quickly.",
    warning: "Stop and contact your landlord, building management, utility company, or emergency service if water overflows, the floor leaks, sewage smell spreads, or the clog does not clear quickly.",
    japanesePhrases: ["トイレが詰まりました。", "水があふれそうです。", "至急確認をお願いします。"],
    phrases: ["トイレが詰まりました。", "水があふれそうです。", "至急確認をお願いします。"],
  },
  {
    id: "air-conditioner-leaking",
    category: "Home Basics",
    title: "Air Conditioner Is Leaking",
    summary: "What to check safely before contacting management about AC water leakage.",
    keywords: ["air conditioner", "AC", "leaking", "water", "appliance"],
    riskLevel: "Medium",
    risk: "Medium",
    time: "10 min",
    diy: "Observe only",
    beforeYouStart: ["Turn the air conditioner off.", "Move electronics and bedding away from dripping water.", "Do not open the unit body."],
    tools: ["Towels", "Bucket", "Phone camera"],
    problem: "Water is dripping from the air conditioner or wall area.",
    steps: ["Turn off the unit and place a towel or bucket under the drip.", "Take photos of the leak, remote settings, and wall area.", "Check only the removable filter if the manual says it is safe.", "Send photos to building management or the landlord."],
    stopAndAskForHelp: "Stop and contact your landlord, building management, utility company, or emergency service if water is near an outlet, the unit smells burnt, sparks, makes unusual sounds, or leakage is heavy.",
    warning: "Stop and contact your landlord, building management, utility company, or emergency service if water is near an outlet, the unit smells burnt, sparks, makes unusual sounds, or leakage is heavy.",
    japanesePhrases: ["エアコンから水が漏れています。", "写真を送ります。", "修理業者の手配をお願いします。"],
    phrases: ["エアコンから水が漏れています。", "写真を送ります。", "修理業者の手配をお願いします。"],
  },
  {
    id: "first-hospital-visit",
    category: "Food & Health",
    title: "First Hospital Visit",
    summary: "A practical guide for choosing a clinic, preparing documents, and explaining symptoms.",
    keywords: ["hospital", "clinic", "health", "insurance", "doctor"],
    riskLevel: "Low",
    risk: "Low",
    time: "25 min",
    diy: "Yes",
    beforeYouStart: ["If symptoms are severe, call emergency services instead of waiting.", "Check whether the clinic accepts your insurance.", "Prepare a short symptom note."],
    tools: ["Health insurance card", "Residence card", "Medication list", "Cash or card"],
    problem: "You need medical help but are unsure how to visit a clinic alone.",
    steps: ["Search for a clinic matching your symptom and language needs.", "Call or check online whether reservations are required.", "Write when symptoms started, pain level, allergies, and current medication.", "Ask the reception what to do next after the visit."],
    stopAndAskForHelp: "Call emergency services for chest pain, trouble breathing, heavy bleeding, loss of consciousness, severe allergic reaction, or any situation that feels urgent.",
    warning: "Call emergency services for chest pain, trouble breathing, heavy bleeding, loss of consciousness, severe allergic reaction, or any situation that feels urgent.",
    japanesePhrases: ["初診です。", "保険証を持っています。", "症状はいつからですか？"],
    phrases: ["初診です。", "保険証を持っています。", "症状はいつからですか？"],
  },
  {
    id: "garbage-sorting",
    category: "Cleaning",
    title: "Garbage Sorting Basics",
    summary: "A first-pass routine for sorting burnable, plastic, bottles, cans, and oversized trash.",
    keywords: ["garbage", "trash", "cleaning", "sorting", "recycling"],
    risk: "Low",
    riskLevel: "Low",
    time: "20 min",
    diy: "Yes",
    beforeYouStart: ["Check your ward or city garbage calendar.", "Do not leave personal documents visible in trash.", "Rinse containers before storing them."],
    tools: ["City garbage calendar", "Transparent bags", "Marker", "Small bins"],
    problem: "You need a simple system for sorting trash without letting it pile up.",
    steps: ["Separate burnable trash, plastics, bottles, cans, and paper.", "Write collection days on a visible note near the door.", "Rinse bottles and cans before storing them.", "Book oversized trash collection before moving or replacing furniture."],
    stopAndAskForHelp: "Ask building management or your city office if you are unsure about batteries, spray cans, sharp objects, or oversized garbage.",
    warning: "Ask building management or your city office if you are unsure about batteries, spray cans, sharp objects, or oversized garbage.",
    japanesePhrases: [],
    phrases: [],
  },
  {
    id: "moving-checklist",
    category: "Moving",
    title: "Moving Checklist",
    summary: "A calm moving sequence for utilities, keys, documents, first-night items, and safety checks.",
    keywords: ["moving", "move", "checklist", "rent", "first night"],
    risk: "Low",
    riskLevel: "Low",
    time: "45 min",
    diy: "Yes",
    beforeYouStart: ["Keep keys, contract papers, and ID in one bag.", "Pack one first-night kit before sealing boxes.", "Photograph the empty room before unpacking."],
    tools: ["First-night bag", "Chargers", "Trash bags", "Contract documents", "Phone camera"],
    problem: "Moving day can become overwhelming if essential items disappear into boxes.",
    steps: ["Schedule electricity, gas, water, and internet before moving day.", "Pack toiletries, towel, pajamas, medicine, chargers, and cash in one visible bag.", "Take photos of walls, floors, appliances, and existing damage.", "Set up light, bedding, water, and phone charging before decorating."],
    stopAndAskForHelp: "Contact building management if keys, locks, gas, electricity, water, or appliance setup seems unclear or unsafe.",
    warning: "Contact building management if keys, locks, gas, electricity, water, or appliance setup seems unclear or unsafe.",
    japanesePhrases: ["引っ越し当日に確認したいです。", "鍵を受け取りました。", "既存の傷を写真で残します。"],
    phrases: ["引っ越し当日に確認したいです。", "鍵を受け取りました。", "既存の傷を写真で残します。"],
  },
  {
    id: "lost-key",
    category: "Emergency",
    title: "Lost Your Key",
    summary: "What to do when you cannot enter your room without making the situation unsafe.",
    keywords: ["lost key", "key", "lock", "emergency", "landlord"],
    risk: "Medium",
    riskLevel: "Medium",
    time: "20 min",
    diy: "No forced entry",
    beforeYouStart: ["Move to a bright public place if it is late.", "Do not try to force the door open.", "Keep your phone charged and contacts visible."],
    tools: ["Phone", "ID", "Rental contract", "Emergency contact"],
    problem: "You lost your key or cannot enter your apartment.",
    steps: ["Check your bag, coat pockets, last cafe, station, and workplace once.", "Call building management, landlord, or the official lock support number.", "Confirm identity requirements and cost before agreeing to locksmith service.", "If you feel unsafe waiting outside, go to a convenience store, station, or trusted public place."],
    stopAndAskForHelp: "Contact building management, your landlord, or police if someone may have stolen your key, your address is identifiable, or you feel unsafe outside.",
    warning: "Contact building management, your landlord, or police if someone may have stolen your key, your address is identifiable, or you feel unsafe outside.",
    japanesePhrases: ["鍵をなくしました。", "部屋に入れません。", "身分証を持っています。"],
    phrases: ["鍵をなくしました。", "部屋に入れません。", "身分証を持っています。"],
  },
  {
    id: "gas-smell",
    category: "Emergency",
    title: "Smell Gas at Home",
    summary: "A high-risk guide for leaving safely and contacting the right service.",
    keywords: ["gas", "smell", "emergency", "utility", "fire"],
    riskLevel: "High",
    risk: "High",
    time: "Immediate",
    diy: "No",
    beforeYouStart: ["Do not use flames.", "Do not switch lights or appliances on or off.", "Open a window only if you can do it immediately and safely."],
    tools: ["Phone after leaving", "Building emergency contact"],
    problem: "You smell gas or suspect a gas leak.",
    steps: ["Stop using gas immediately.", "Leave the room and move away from the suspected leak.", "Call the gas company emergency number, building management, or emergency service from outside.", "Do not re-enter until professionals say it is safe."],
    stopAndAskForHelp: "Stop and contact your landlord, building management, utility company, or emergency service. Do not try to repair gas equipment yourself.",
    warning: "Stop and contact your landlord, building management, utility company, or emergency service. Do not try to repair gas equipment yourself.",
    japanesePhrases: ["ガスのにおいがします。", "ガス漏れの可能性があります。", "外に避難しました。"],
    phrases: ["ガスのにおいがします。", "ガス漏れの可能性があります。", "外に避難しました。"],
  },
  {
    id: "breaker-keeps-tripping",
    category: "Emergency",
    title: "Breaker Keeps Tripping",
    summary: "How to respond when electricity repeatedly cuts out without touching wiring.",
    keywords: ["electricity", "breaker", "power", "outage", "appliance fault"],
    riskLevel: "High",
    risk: "High",
    time: "Immediate",
    diy: "No wiring",
    beforeYouStart: ["Do not touch exposed wires.", "Unplug devices only if the outlet area is dry and safe.", "Keep away from burning smells or heat."],
    tools: ["Phone", "Flashlight", "Utility bill or provider name"],
    problem: "The breaker trips repeatedly, power cuts out, or an appliance may be unsafe.",
    steps: ["Turn off and unplug the appliance you were using if safe.", "Move away from outlets, sparks, heat, or burning smell.", "Take note of which room or device was involved.", "Contact building management or the electricity provider."],
    stopAndAskForHelp: "Stop and contact your landlord, building management, utility company, or emergency service. Do not open electrical panels, repair wiring, or keep using a dangerous appliance.",
    warning: "Stop and contact your landlord, building management, utility company, or emergency service. Do not open electrical panels, repair wiring, or keep using a dangerous appliance.",
    japanesePhrases: ["ブレーカーが何度も落ちます。", "焦げたにおいがします。", "電気会社に連絡したいです。"],
    phrases: ["ブレーカーが何度も落ちます。", "焦げたにおいがします。", "電気会社に連絡したいです。"],
  },
  {
    id: "rent-contract-basics",
    category: "Money & Budget",
    title: "Rent Contract Basics",
    summary: "A quick guide to fees, renewal terms, guarantors, and questions to ask before signing.",
    keywords: ["rent", "contract", "apartment", "budget", "guarantor"],
    riskLevel: "Low",
    risk: "Low",
    time: "25 min",
    diy: "Yes",
    beforeYouStart: ["Read fees slowly.", "Ask for written explanations.", "Do not sign under pressure."],
    tools: ["Contract draft", "Fee list", "Translation app", "Notebook"],
    problem: "You want to understand the money and obligations before signing a rental contract.",
    steps: ["List rent, management fee, deposit, key money, insurance, guarantor fee, and renewal fee.", "Check cancellation rules, repair responsibilities, and guest or noise rules.", "Ask what happens if you lose a key or need emergency repair.", "Take time to compare the contract with your monthly budget."],
    stopAndAskForHelp: "Ask a trusted person, school office, workplace support, or housing consultation service if fees are unclear or you feel pressured.",
    warning: "Ask a trusted person, school office, workplace support, or housing consultation service if fees are unclear or you feel pressured.",
    japanesePhrases: ["契約内容を確認したいです。", "この費用は何ですか？", "少し考える時間をください。"],
    phrases: ["契約内容を確認したいです。", "この費用は何ですか？", "少し考える時間をください。"],
  },
];

export const places = [
  {
    id: "mori-cafe",
    name: "Mori Window Cafe",
    category: "Cafe",
    distance: "8 min",
    budget: "1000-1800 yen",
    open: true,
    safe: 94,
    solo: 96,
    women: 95,
    area: "Kichijoji",
    address: "2-14 Kichijoji Minamicho, Musashino",
    hours: "08:00-20:30",
    reason: "Window seats, soft morning light, staff visibility, and a calm flow of solo visitors.",
    womenFriendly: "Well-lit entrance, clean restroom, no pressure to order quickly, and staff check on late guests.",
    soloReason: "Small tables, counter seats, quiet reading mood, and outlets near the wall.",
    review: "I stayed for an hour with a book and felt completely unhurried.",
  },
  {
    id: "tsuki-books",
    name: "Tsuki Books",
    category: "Bookstore",
    distance: "11 min",
    budget: "0-2500 yen",
    open: true,
    safe: 91,
    solo: 98,
    women: 92,
    area: "Shimokitazawa",
    address: "4-3 Kitazawa, Setagaya",
    hours: "11:00-21:00",
    reason: "Gentle staff, narrow but visible aisles, late hours, and a small seating nook.",
    womenFriendly: "Staff desk faces the entrance and the shop is on a bright street.",
    soloReason: "Browsing alone feels natural, with zines, essays, and small gift shelves.",
    review: "A good place to reset before going home.",
  },
  {
    id: "hana-room",
    name: "Hana Room",
    category: "Flower Shop",
    distance: "6 min",
    budget: "600-2000 yen",
    open: true,
    safe: 89,
    solo: 90,
    women: 96,
    area: "Ueno",
    address: "1-9 Ueno Sakuragi, Taito",
    hours: "10:00-19:00",
    reason: "Small bouquets, friendly explanations, and a street-facing counter.",
    womenFriendly: "Staff are used to solo customers and can make small budget bouquets.",
    soloReason: "A quick, gentle stop that makes a room feel cared for.",
    review: "I bought one flower after a hard day and it changed the whole room.",
  },
  {
    id: "nagi-museum",
    name: "Nagi Museum Hour",
    category: "Museum",
    distance: "18 min",
    budget: "1200 yen",
    open: false,
    safe: 93,
    solo: 97,
    women: 91,
    area: "Ueno",
    address: "7-20 Ueno Park, Taito",
    hours: "09:30-17:30",
    reason: "Clear routes, lockers, staff presence, and no awkwardness visiting alone.",
    womenFriendly: "Visible attendants and safe restroom access throughout the building.",
    soloReason: "Good for moving slowly without explaining your pace to anyone.",
    review: "Perfect for an inspiration day.",
  },
  {
    id: "riverside-park",
    name: "Riverside Park",
    category: "Park",
    distance: "15 min",
    budget: "0 yen",
    open: true,
    safe: 88,
    solo: 94,
    women: 89,
    area: "Kichijoji",
    address: "Inokashira Park edge, Musashino",
    hours: "05:00-23:00",
    reason: "Open sightlines, families nearby during the day, and several exits toward busy streets.",
    womenFriendly: "Good daytime visibility and many nearby cafes for a quick safe stop.",
    soloReason: "Easy to sit, sketch, read, or walk without feeling watched.",
    review: "A soft reset place before going back home.",
  },
  {
    id: "luna-gym",
    name: "Luna Studio Gym",
    category: "Gym",
    distance: "13 min",
    budget: "1800 yen trial",
    open: true,
    safe: 90,
    solo: 88,
    women: 94,
    area: "Shinjuku",
    address: "3-8 Shinjuku, Tokyo",
    hours: "07:00-22:00",
    reason: "Bright reception, women-friendly classes, and clear staff presence near lockers.",
    womenFriendly: "Staff explain first-visit flow and locker areas are well monitored.",
    soloReason: "Beginner classes make it easy to arrive alone and leave at your own pace.",
    review: "I did not feel awkward joining alone.",
  },
  {
    id: "sora-clinic",
    name: "Sora Women's Clinic",
    category: "Clinic",
    distance: "9 min",
    budget: "Insurance accepted",
    open: true,
    safe: 95,
    solo: 87,
    women: 98,
    area: "Ueno",
    address: "2-6 Ueno, Taito",
    hours: "09:00-18:00",
    reason: "Clear appointment flow, private waiting area, and multilingual intake cards.",
    womenFriendly: "Female doctor days are listed clearly and staff explain privacy options.",
    soloReason: "Check-in is simple and does not require bringing someone with you.",
    review: "The front desk was calm and kind.",
  },
  {
    id: "yuzu-table",
    name: "Yuzu Solo Table",
    category: "Solo Restaurant",
    distance: "10 min",
    budget: "1200-2600 yen",
    open: true,
    safe: 87,
    solo: 99,
    women: 90,
    area: "Shimokitazawa",
    address: "5-11 Kitazawa, Setagaya",
    hours: "11:30-22:00",
    reason: "Counter seating, friendly staff, and a lot of one-person dinner guests.",
    womenFriendly: "Staff check seating preference and the entrance faces a lively street.",
    soloReason: "Single seats are intentional, not an afterthought.",
    review: "Dinner alone felt normal here.",
  },
  {
    id: "lantern-walk",
    name: "Lantern Walk Street",
    category: "Night Walk Spot",
    distance: "7 min",
    budget: "0 yen",
    open: true,
    safe: 86,
    solo: 90,
    women: 87,
    area: "Kichijoji",
    address: "Station north shopping street",
    hours: "18:00-23:00",
    reason: "Bright storefronts, steady foot traffic, and several convenience stores along the route.",
    womenFriendly: "Easy exits to station gates and staffed shops stay open late.",
    soloReason: "Good for a short romanticized walk without entering quiet roads.",
    review: "I used it as my safe route home.",
  },
];

export const dayRules = {
  Peace: ["Cafe", "Bookstore", "Flower Shop", "Park"],
  Explore: ["Museum", "Vintage Store", "Cafe", "Bookstore"],
  Inspiration: ["Museum", "Bookstore", "Flower Shop", "Cafe"],
  "Self-care": ["Gym", "Clinic", "Healthy Cafe", "Park"],
  "Romanticize life": ["Flower Shop", "Cafe", "Park", "Solo Restaurant"],
  "Night walk": ["Cafe", "Bookstore", "Convenience Store", "Night Walk Spot"],
};

export const daySuggestions = [
  {
    id: "gentle-kichijoji-reset",
    title: "Gentle Kichijoji Reset",
    mood: "Peace",
    area: "Kichijoji",
    duration: "Half day",
    budget: "3000 yen",
    description: "A slow afternoon for coffee, air, and a safe walk back toward the station.",
    includes: ["Cafe", "Park", "Night Walk Spot"],
    routePlaceholder: "Route placeholder: Mori Window Cafe → Riverside Park → Lantern Walk Street.",
    stops: [
      {
        time: "11:00",
        title: "Mori Window Cafe",
        type: "Cafe",
        description: "Start with a window seat, warm drink, and a quiet reset.",
      },
      {
        time: "13:00",
        title: "Riverside Park",
        type: "Park",
        description: "Take a visible daytime walk with open exits and nearby cafes.",
      },
      {
        time: "15:00",
        title: "Lantern Walk Street",
        type: "Night Walk Spot",
        description: "Check the brighter route you can reuse on a late evening.",
      },
    ],
  },
  {
    id: "bookish-shimokitazawa",
    title: "Bookish Solo Afternoon",
    mood: "Inspiration",
    area: "Shimokitazawa",
    duration: "2h",
    budget: "3000 yen",
    description: "A compact solo plan for browsing, noticing small details, and eating without rushing.",
    includes: ["Bookstore", "Flower Shop", "Solo Restaurant"],
    routePlaceholder: "Route placeholder: Tsuki Books → small flower stop → Yuzu Solo Table.",
    stops: [
      {
        time: "13:00",
        title: "Tsuki Books",
        type: "Bookstore",
        description: "Browse essays, zines, and a shelf that feels like it found you first.",
      },
      {
        time: "14:00",
        title: "Small flower stop",
        type: "Flower Shop",
        description: "Choose one stem for your room instead of a full bouquet.",
      },
      {
        time: "15:00",
        title: "Yuzu Solo Table",
        type: "Solo Restaurant",
        description: "End with an easy counter seat made for one-person dinners.",
      },
    ],
  },
  {
    id: "ueno-soft-inspiration",
    title: "Ueno Soft Inspiration",
    mood: "Explore",
    area: "Ueno",
    duration: "Half day",
    budget: "5000 yen",
    description: "A museum-led day with flowers and a quiet pause before heading home.",
    includes: ["Museum", "Flower Shop", "Cafe"],
    routePlaceholder: "Route placeholder: Nagi Museum Hour → Hana Room → quiet cafe break.",
    stops: [
      {
        time: "10:30",
        title: "Nagi Museum Hour",
        type: "Museum",
        description: "Move slowly through one exhibition without needing to explain your pace.",
      },
      {
        time: "13:00",
        title: "Hana Room",
        type: "Flower Shop",
        description: "Pick a small bouquet with a clear budget and kind staff guidance.",
      },
      {
        time: "15:00",
        title: "Quiet cafe break",
        type: "Cafe",
        description: "Write down one thing you want to bring back into your room.",
      },
    ],
  },
  {
    id: "shinjuku-self-care-evening",
    title: "Self-care Evening",
    mood: "Self-care",
    area: "Shinjuku",
    duration: "2h",
    budget: "5000 yen",
    description: "A practical evening for moving your body, eating well, and leaving by a bright route.",
    includes: ["Gym", "Healthy Cafe", "Safe Route"],
    routePlaceholder: "Route placeholder: Luna Studio Gym → healthy cafe → staffed station exit.",
    stops: [
      {
        time: "18:00",
        title: "Luna Studio Gym",
        type: "Gym",
        description: "Choose a beginner-friendly class with clear staff support.",
      },
      {
        time: "19:15",
        title: "Healthy cafe dinner",
        type: "Healthy Cafe",
        description: "Eat somewhere bright, simple, and comfortable for arriving alone.",
      },
      {
        time: "20:15",
        title: "Staffed station exit",
        type: "Safe Route",
        description: "Start the route home from a staffed, well-lit entrance.",
      },
    ],
  },
];

export const areas = ["Shinjuku", "Kichijoji", "Ueno", "Shimokitazawa"];
export const times = ["2h", "Half day", "Full day"];
export const budgets = ["1000 yen", "3000 yen", "5000 yen"];
export const moods = Object.keys(dayRules);
export const livingCategories = ["Home Basics", "Money & Budget", "Food & Health", "Cleaning", "Moving", "Emergency"];
export const placeCategories = ["All", "Cafe", "Bookstore", "Flower", "Park", "Gym", "More"];
export const categoryMap = {
  All: "All",
  Flower: "Flower Shop",
  More: "More",
};
export const categoryIcons = {
  All: "⌂",
  Cafe: "☕",
  Bookstore: "▤",
  Flower: "✿",
  Park: "♧",
  Gym: "∞",
  More: "…",
};

export const favoritePlaceIds = ["mori-cafe", "hana-room"];

export const savedDayPlans = [
  {
    id: "day-1",
    title: "Soft Kichijoji afternoon",
    mood: "Peace",
    area: "Kichijoji",
    stops: ["11:00 Cafe", "13:00 Bookstore", "15:00 Flower Shop", "16:00 Park"],
  },
];
