export const safetyGuides = [
  {
    id: "train",
    icon: "🚇",
    title: "Train Harassment",
    subtitle: "Someone is touching, blocking, or following you on the train.",
    phrase: "やめてください！",
    steps: [
      ["First Step", "Move toward a crowded area, the door, or another carriage as soon as you can."],
      ["Say it loudly", "Use a clear, direct phrase. You do not need to be polite when you are unsafe."],
      ["Ask for help", "Tell a station staff member, nearby passenger, or police officer what happened."],
      ["Save evidence", "Record the time, train line, carriage number, station, and any details you remember."],
    ],
  },
  {
    id: "followed",
    icon: "🚶",
    title: "Being Followed",
    subtitle: "You feel someone is repeatedly following your route.",
    phrase: "ついてこないでください。",
    steps: [
      ["First Step", "Do not go home. Turn toward a bright store, station gate, police box, or busy street."],
      ["Check safely", "Change direction once and notice if the person mirrors you. Do not confront alone."],
      ["Ask for help", "Enter a convenience store or cafe and tell staff: someone may be following me."],
      ["Share location", "Send your current location to an emergency contact and keep your phone visible."],
    ],
  },
  {
    id: "night",
    icon: "🌃",
    title: "Walking Home",
    subtitle: "You are going home late and want a safer route.",
    phrase: "近くまで一緒にいてもらえますか？",
    steps: [
      ["First Step", "Choose lit streets, stations, convenience stores, and roads with people nearby."],
      ["Stay connected", "Start a fake call or real call before leaving the station or building."],
      ["Avoid shortcuts", "Skip quiet parks, underpasses, empty alleys, and stairways even if they are faster."],
      ["Prepare arrival", "Have keys ready before the door and look around before entering your building."],
    ],
  },
  {
    id: "door",
    icon: "🏠",
    title: "Stranger at Door",
    subtitle: "Someone is ringing or knocking and you are not expecting anyone.",
    phrase: "どちら様ですか？用件を教えてください。",
    steps: [
      ["First Step", "Keep the door locked. Do not open the door chain or confirm that you are alone."],
      ["Ask clearly", "Ask for name, company, and purpose through the door or intercom."],
      ["Verify", "If they claim delivery, building staff, or utility work, check through official contact channels."],
      ["Escalate", "If they do not leave, call building management, a nearby contact, or police."],
    ],
  },
  {
    id: "ride",
    icon: "🚕",
    title: "Unsafe Ride",
    subtitle: "A taxi or rideshare route or driver behavior feels wrong.",
    phrase: "ここで降ります。",
    steps: [
      ["First Step", "Share your live location and keep the route open on your own map."],
      ["Create friction", "Call someone and state the car plate, driver name, and route out loud."],
      ["Exit safely", "Ask to stop at a bright convenience store, station, hotel, or busy crossing."],
      ["Report", "Save receipt, plate, time, and route. Report the driver through the service or police."],
    ],
  },
  {
    id: "emergency",
    icon: "🆘",
    title: "Emergency",
    subtitle: "You need immediate help or cannot safely leave.",
    phrase: "助けてください！警察を呼んでください！",
    steps: [
      ["First Step", "Call 110 for police in Japan. If injured or in medical danger, call 119."],
      ["Make yourself visible", "Move toward light, people, cameras, or an open business if possible."],
      ["Use short words", "Say where you are, what is happening, and what you need right now."],
      ["Do not delay", "If you feel in immediate danger, use emergency services before app features."],
    ],
  },
];

export const callers = [
  {
    id: "mom",
    name: "Mom",
    avatar: "M",
    role: "Warm and direct",
    lines: ["Are you there?", "I am nearby now.", "Can you come outside?", "Stay on the phone with me."],
  },
  {
    id: "friend",
    name: "Mina",
    avatar: "M",
    role: "Close friend",
    lines: ["Hey, I can see your location.", "I am walking toward you.", "Keep talking to me.", "Let's meet at the entrance."],
  },
  {
    id: "roommate",
    name: "Roommate",
    avatar: "R",
    role: "At home",
    lines: ["I am waiting downstairs.", "Do you want me to call you?", "Don't come up alone.", "Send me the building entrance."],
  },
  {
    id: "boss",
    name: "Boss",
    avatar: "B",
    role: "Formal excuse",
    lines: ["Can you join the call now?", "We need you back online.", "Please step out and call me.", "I will stay connected."],
  },
];

export const livingGuides = [
  {
    id: "apartment-check",
    category: "Rent",
    title: "Apartment viewing safety check",
    risk: "Low",
    time: "20 min",
    diy: "Yes",
    tools: ["Phone camera", "Checklist", "Station map"],
    problem: "You want to choose a room that supports daily independence, not just a pretty layout.",
    steps: ["Visit once during daylight and once near evening if possible.", "Check street lighting, entrance locks, elevator visibility, and nearby convenience stores.", "Test phone signal inside the room and near the entrance.", "Ask how repairs, lost keys, and emergency notices are handled."],
    warning: "If a listing agent pressures you to decide immediately, step away and compare options.",
    phrases: ["この周辺は夜も明るいですか？", "女性の一人暮らしでも安心ですか？"],
  },
  {
    id: "electricity",
    category: "Utilities",
    title: "Electric bill suddenly too high",
    risk: "Low",
    time: "15 min",
    diy: "Yes",
    tools: ["Recent bill", "Breaker panel", "Appliance list"],
    problem: "You need to identify whether the cost comes from heating, appliance use, contract settings, or a meter issue.",
    steps: ["Compare this month with the same season last year if available.", "Check air conditioner mode, water heater settings, and always-on appliances.", "Confirm your electricity plan and peak-hour pricing.", "Contact the provider if the number is far outside normal usage."],
    warning: "Do not touch wiring or open electrical fixtures yourself.",
    phrases: ["電気料金について確認したいです。", "使用量が急に増えた理由を知りたいです。"],
  },
  {
    id: "toilet",
    category: "Home Fix",
    title: "Toilet keeps running",
    risk: "Low",
    time: "10 min",
    diy: "Yes",
    tools: ["Rubber gloves", "Towel", "Phone light"],
    problem: "Water keeps flowing after flushing, which can raise your water bill and become stressful at night.",
    steps: ["Open the tank lid carefully and place it on a towel.", "Check whether the flapper is closing fully.", "Lift and release the float gently to see if water stops.", "If it does not stop, close the water valve and contact management."],
    warning: "Call building management if you see leaking on the floor or if the valve is stuck.",
    phrases: ["トイレの水が止まりません。", "修理をお願いできますか？"],
  },
  {
    id: "mold",
    category: "Cleaning",
    title: "Prevent bathroom mold",
    risk: "Low",
    time: "8 min/day",
    diy: "Yes",
    tools: ["Vent fan", "Squeegee", "Mold spray"],
    problem: "Small bathrooms can hold moisture and create mold quickly.",
    steps: ["Run the ventilation fan during and after showers.", "Wipe walls and mirror edges after bathing.", "Keep shampoo bottles off the floor when possible.", "Clean silicone edges weekly before dark spots spread."],
    warning: "Use ventilation and gloves when using cleaning spray.",
    phrases: ["浴室のカビを防ぎたいです。", "換気扇の使い方を教えてください。"],
  },
  {
    id: "moving",
    category: "Moving",
    title: "First-night moving kit",
    risk: "Low",
    time: "30 min",
    diy: "Yes",
    tools: ["Small suitcase", "Chargers", "Towel", "Medication"],
    problem: "Moving day can leave essential things buried in boxes.",
    steps: ["Pack one visible bag with chargers, pajamas, towel, toiletries, medication, and trash bags.", "Keep keys, contract documents, and cash together.", "Take photos of the empty room before unpacking.", "Set up light, bedding, and water before anything decorative."],
    warning: "Do not let movers or delivery staff see sensitive documents or spare keys.",
    phrases: ["荷物はここに置いてください。", "確認してからサインします。"],
  },
  {
    id: "earthquake",
    category: "Disaster",
    title: "Earthquake basics for your room",
    risk: "Medium",
    time: "40 min",
    diy: "Mostly",
    tools: ["Emergency bag", "Water", "Furniture stoppers"],
    problem: "You need your room to support you during shaking, power loss, or evacuation.",
    steps: ["Keep heavy items low and secure shelves near your bed.", "Prepare water, snacks, flashlight, battery, medication, and copies of documents.", "Learn your nearest evacuation site and building exit route.", "Choose one check-in contact for disaster messages."],
    warning: "For gas smell, structural damage, or injury, leave and contact emergency services.",
    phrases: ["避難場所はどこですか？", "ガスの元栓を確認したいです。"],
  },
];

export const places = [
  {
    id: "mori-cafe",
    name: "Mori Window Cafe",
    category: "Cafe",
    distance: "8 min",
    budget: "1000-1800 yen",
    open: true,
    safe: 94,
    solo: 96,
    women: 95,
    area: "Kichijoji",
    address: "2-14 Kichijoji Minamicho, Musashino",
    hours: "08:00-20:30",
    reason: "Window seats, soft morning light, staff visibility, and a calm flow of solo visitors.",
    womenFriendly: "Well-lit entrance, clean restroom, no pressure to order quickly, and staff check on late guests.",
    soloReason: "Small tables, counter seats, quiet reading mood, and outlets near the wall.",
    review: "I stayed for an hour with a book and felt completely unhurried.",
  },
  {
    id: "tsuki-books",
    name: "Tsuki Books",
    category: "Bookstore",
    distance: "11 min",
    budget: "0-2500 yen",
    open: true,
    safe: 91,
    solo: 98,
    women: 92,
    area: "Shimokitazawa",
    address: "4-3 Kitazawa, Setagaya",
    hours: "11:00-21:00",
    reason: "Gentle staff, narrow but visible aisles, late hours, and a small seating nook.",
    womenFriendly: "Staff desk faces the entrance and the shop is on a bright street.",
    soloReason: "Browsing alone feels natural, with zines, essays, and small gift shelves.",
    review: "A good place to reset before going home.",
  },
  {
    id: "hana-room",
    name: "Hana Room",
    category: "Flower Shop",
    distance: "6 min",
    budget: "600-2000 yen",
    open: true,
    safe: 89,
    solo: 90,
    women: 96,
    area: "Ueno",
    address: "1-9 Ueno Sakuragi, Taito",
    hours: "10:00-19:00",
    reason: "Small bouquets, friendly explanations, and a street-facing counter.",
    womenFriendly: "Staff are used to solo customers and can make small budget bouquets.",
    soloReason: "A quick, gentle stop that makes a room feel cared for.",
    review: "I bought one flower after a hard day and it changed the whole room.",
  },
  {
    id: "nagi-museum",
    name: "Nagi Museum Hour",
    category: "Museum",
    distance: "18 min",
    budget: "1200 yen",
    open: false,
    safe: 93,
    solo: 97,
    women: 91,
    area: "Ueno",
    address: "7-20 Ueno Park, Taito",
    hours: "09:30-17:30",
    reason: "Clear routes, lockers, staff presence, and no awkwardness visiting alone.",
    womenFriendly: "Visible attendants and safe restroom access throughout the building.",
    soloReason: "Good for moving slowly without explaining your pace to anyone.",
    review: "Perfect for an inspiration day.",
  },
  {
    id: "riverside-park",
    name: "Riverside Park",
    category: "Park",
    distance: "15 min",
    budget: "0 yen",
    open: true,
    safe: 88,
    solo: 94,
    women: 89,
    area: "Kichijoji",
    address: "Inokashira Park edge, Musashino",
    hours: "05:00-23:00",
    reason: "Open sightlines, families nearby during the day, and several exits toward busy streets.",
    womenFriendly: "Good daytime visibility and many nearby cafes for a quick safe stop.",
    soloReason: "Easy to sit, sketch, read, or walk without feeling watched.",
    review: "A soft reset place before going back home.",
  },
  {
    id: "luna-gym",
    name: "Luna Studio Gym",
    category: "Gym",
    distance: "13 min",
    budget: "1800 yen trial",
    open: true,
    safe: 90,
    solo: 88,
    women: 94,
    area: "Shinjuku",
    address: "3-8 Shinjuku, Tokyo",
    hours: "07:00-22:00",
    reason: "Bright reception, women-friendly classes, and clear staff presence near lockers.",
    womenFriendly: "Staff explain first-visit flow and locker areas are well monitored.",
    soloReason: "Beginner classes make it easy to arrive alone and leave at your own pace.",
    review: "I did not feel awkward joining alone.",
  },
  {
    id: "sora-clinic",
    name: "Sora Women's Clinic",
    category: "Clinic",
    distance: "9 min",
    budget: "Insurance accepted",
    open: true,
    safe: 95,
    solo: 87,
    women: 98,
    area: "Ueno",
    address: "2-6 Ueno, Taito",
    hours: "09:00-18:00",
    reason: "Clear appointment flow, private waiting area, and multilingual intake cards.",
    womenFriendly: "Female doctor days are listed clearly and staff explain privacy options.",
    soloReason: "Check-in is simple and does not require bringing someone with you.",
    review: "The front desk was calm and kind.",
  },
  {
    id: "yuzu-table",
    name: "Yuzu Solo Table",
    category: "Solo Restaurant",
    distance: "10 min",
    budget: "1200-2600 yen",
    open: true,
    safe: 87,
    solo: 99,
    women: 90,
    area: "Shimokitazawa",
    address: "5-11 Kitazawa, Setagaya",
    hours: "11:30-22:00",
    reason: "Counter seating, friendly staff, and a lot of one-person dinner guests.",
    womenFriendly: "Staff check seating preference and the entrance faces a lively street.",
    soloReason: "Single seats are intentional, not an afterthought.",
    review: "Dinner alone felt normal here.",
  },
  {
    id: "lantern-walk",
    name: "Lantern Walk Street",
    category: "Night Walk Spot",
    distance: "7 min",
    budget: "0 yen",
    open: true,
    safe: 86,
    solo: 90,
    women: 87,
    area: "Kichijoji",
    address: "Station north shopping street",
    hours: "18:00-23:00",
    reason: "Bright storefronts, steady foot traffic, and several convenience stores along the route.",
    womenFriendly: "Easy exits to station gates and staffed shops stay open late.",
    soloReason: "Good for a short romanticized walk without entering quiet roads.",
    review: "I used it as my safe route home.",
  },
];

export const dayRules = {
  Peace: ["Cafe", "Bookstore", "Flower Shop", "Park"],
  Explore: ["Museum", "Vintage Store", "Cafe", "Bookstore"],
  Inspiration: ["Museum", "Bookstore", "Flower Shop", "Cafe"],
  "Self-care": ["Gym", "Clinic", "Healthy Cafe", "Park"],
  "Romanticize life": ["Flower Shop", "Cafe", "Park", "Solo Restaurant"],
  "Night walk": ["Cafe", "Bookstore", "Convenience Store", "Night Walk Spot"],
};

export const areas = ["Shinjuku", "Kichijoji", "Ueno", "Shimokitazawa"];
export const times = ["2h", "Half day", "Full day"];
export const budgets = ["1000 yen", "3000 yen", "5000 yen"];
export const moods = Object.keys(dayRules);
export const livingCategories = ["Rent", "Utilities", "Home Fix", "Cleaning", "Moving", "Disaster"];
export const placeCategories = ["All", "Cafe", "Bookstore", "Flower", "Park", "Gym", "More"];
export const categoryMap = {
  All: "All",
  Flower: "Flower Shop",
  More: "More",
};
export const categoryIcons = {
  All: "⌂",
  Cafe: "☕",
  Bookstore: "▤",
  Flower: "✿",
  Park: "♧",
  Gym: "∞",
  More: "…",
};

export const favoritePlaceIds = ["mori-cafe", "hana-room"];

export const savedDayPlans = [
  {
    id: "day-1",
    title: "Soft Kichijoji afternoon",
    mood: "Peace",
    area: "Kichijoji",
    stops: ["11:00 Cafe", "13:00 Bookstore", "15:00 Flower Shop", "16:00 Park"],
  },
];
