export const safetyGuides = [
  {
    id: "train",
    icon: "🚇",
    title: "Train Harassment",
    subtitle: "Someone is touching, blocking, or following you on the train.",
    phrase: "やめてください！",
    steps: [
      ["First Step", "Move toward a crowded area, the door, or another carriage as soon as you can."],
      ["Say it loudly", "Use a clear, direct phrase. You do not need to be polite when you are unsafe."],
      ["Ask for help", "Tell a station staff member, nearby passenger, or police officer what happened."],
      ["Save evidence", "Record the time, train line, carriage number, station, and any details you remember."],
    ],
  },
  {
    id: "followed",
    icon: "🚶",
    title: "Being Followed",
    subtitle: "You feel someone is repeatedly following your route.",
    phrase: "ついてこないでください。",
    steps: [
      ["First Step", "Do not go home. Turn toward a bright store, station gate, police box, or busy street."],
      ["Check safely", "Change direction once and notice if the person mirrors you. Do not confront alone."],
      ["Ask for help", "Enter a convenience store or cafe and tell staff: someone may be following me."],
      ["Share location", "Send your current location to an emergency contact and keep your phone visible."],
    ],
  },
  {
    id: "night",
    icon: "🌃",
    title: "Walking Home",
    subtitle: "You are going home late and want a safer route.",
    phrase: "近くまで一緒にいてもらえますか？",
    steps: [
      ["First Step", "Choose lit streets, stations, convenience stores, and roads with people nearby."],
      ["Stay connected", "Start Safety Call or a real call before leaving the station or building."],
      ["Avoid shortcuts", "Skip quiet parks, underpasses, empty alleys, and stairways even if they are faster."],
      ["Prepare arrival", "Have keys ready before the door and look around before entering your building."],
    ],
  },
  {
    id: "door",
    icon: "🏠",
    title: "Stranger at Door",
    subtitle: "Someone is ringing or knocking and you are not expecting anyone.",
    phrase: "どちら様ですか？用件を教えてください。",
    steps: [
      ["First Step", "Keep the door locked. Do not open the door chain or confirm that you are alone."],
      ["Ask clearly", "Ask for name, company, and purpose through the door or intercom."],
      ["Verify", "If they claim delivery, building staff, or utility work, check through official contact channels."],
      ["Escalate", "If they do not leave, call building management, a nearby contact, or police."],
    ],
  },
  {
    id: "ride",
    icon: "🚕",
    title: "Unsafe Ride",
    subtitle: "A taxi or rideshare route or driver behavior feels wrong.",
    phrase: "ここで降ります。",
    steps: [
      ["First Step", "Share your live location and keep the route open on your own map."],
      ["Create friction", "Call someone and state the car plate, driver name, and route out loud."],
      ["Exit safely", "Ask to stop at a bright convenience store, station, hotel, or busy crossing."],
      ["Report", "Save receipt, plate, time, and route. Report the driver through the service or police."],
    ],
  },
  {
    id: "emergency",
    icon: "🆘",
    title: "Emergency",
    subtitle: "You need immediate help or cannot safely leave.",
    phrase: "助けてください！警察を呼んでください！",
    steps: [
      ["First Step", "Call 110 for police in Japan. If injured or in medical danger, call 119."],
      ["Make yourself visible", "Move toward light, people, cameras, or an open business if possible."],
      ["Use short words", "Say where you are, what is happening, and what you need right now."],
      ["Do not delay", "If you feel in immediate danger, use emergency services before app features."],
    ],
  },
];

export const livingGuides = [
  {
    id: "washing-machine-drain",
    category: "Home Basics",
    title: "Washing Machine Won’t Drain",
    summary: "A calm check for standing water, lint filters, and when to stop before touching appliance parts.",
    keywords: ["washing machine", "laundry", "drain", "water", "appliance"],
    riskLevel: "Medium",
    risk: "Medium",
    time: "15 min",
    diy: "Limited",
    beforeYouStart: ["Turn the machine off.", "Keep your hands dry around the outlet.", "Place towels near the machine if water is visible."],
    tools: ["Towels", "Small bowl", "Flashlight", "Manual if available"],
    problem: "The washing machine has water inside or will not complete the drain cycle.",
    steps: ["Pause the machine and unplug it only if the plug area is dry and easy to reach.", "Check whether the drain hose is bent or pressed behind the machine.", "Look for a visible lint filter panel and follow the machine manual only if it is easy to open.", "Take a photo of any error code before contacting support."],
    stopAndAskForHelp: "Stop and contact your landlord, building management, utility company, or emergency service if water reaches an outlet, you smell burning, the machine sparks, or there is major water leakage.",
    warning: "Stop and contact your landlord, building management, utility company, or emergency service if water reaches an outlet, you smell burning, the machine sparks, or there is major water leakage.",
    japanesePhrases: ["洗濯機の水が排水されません。", "エラーコードが出ています。", "修理をお願いできますか？"],
    phrases: ["洗濯機の水が排水されません。", "エラーコードが出ています。", "修理をお願いできますか？"],
  },
  {
    id: "utilities-setup",
    category: "Money & Budget",
    title: "How to Set Up Utilities",
    summary: "A first-apartment checklist for electricity, gas, water, internet, and safe contact points.",
    keywords: ["utilities", "electricity", "gas", "water", "internet", "set up", "moving"],
    riskLevel: "Medium",
    risk: "Medium",
    time: "30 min",
    diy: "Admin only",
    beforeYouStart: ["Prepare your address, move-in date, phone number, and residence card if needed.", "Ask your landlord which providers serve the building.", "Do not open gas valves or electrical panels yourself."],
    tools: ["Rental contract", "Phone", "Provider website", "Move-in date"],
    problem: "You need to start basic home services without missing a safety step.",
    steps: ["Confirm which utilities are already connected by the building.", "Apply for electricity and water using official provider forms.", "Book a gas opening appointment if gas is used in the room.", "Save emergency phone numbers for electricity, gas, and building management."],
    stopAndAskForHelp: "Stop and contact your landlord, building management, utility company, or emergency service for gas opening, electrical faults, gas smell, damaged meters, or unclear utility equipment.",
    warning: "Stop and contact your landlord, building management, utility company, or emergency service for gas opening, electrical faults, gas smell, damaged meters, or unclear utility equipment.",
    japanesePhrases: ["電気・ガス・水道の開始手続きをしたいです。", "ガスの開栓予約をお願いします。", "管理会社に確認します。"],
    phrases: ["電気・ガス・水道の開始手続きをしたいです。", "ガスの開栓予約をお願いします。", "管理会社に確認します。"],
  },
  {
    id: "toilet-clogged",
    category: "Home Basics",
    title: "Toilet Is Clogged",
    summary: "Simple first steps for a clogged toilet, with clear stop points for overflow or leakage.",
    keywords: ["toilet", "clogged", "bathroom", "water", "plunger"],
    riskLevel: "Medium",
    risk: "Medium",
    time: "15 min",
    diy: "Limited",
    beforeYouStart: ["Do not flush repeatedly.", "Put towels on the floor.", "Keep cleaning products separate and never mix chemicals."],
    tools: ["Rubber gloves", "Plunger", "Towels", "Trash bag"],
    problem: "The toilet water is rising, draining slowly, or not clearing after one flush.",
    steps: ["Stop flushing and wait for the water level to settle.", "Use a plunger gently with enough water to cover the rubber cup.", "Try several slow pushes rather than forceful splashing.", "Clean the area and wash your hands thoroughly if the water clears."],
    stopAndAskForHelp: "Stop and contact your landlord, building management, utility company, or emergency service if water overflows, the floor leaks, sewage smell spreads, or the clog does not clear quickly.",
    warning: "Stop and contact your landlord, building management, utility company, or emergency service if water overflows, the floor leaks, sewage smell spreads, or the clog does not clear quickly.",
    japanesePhrases: ["トイレが詰まりました。", "水があふれそうです。", "至急確認をお願いします。"],
    phrases: ["トイレが詰まりました。", "水があふれそうです。", "至急確認をお願いします。"],
  },
  {
    id: "air-conditioner-leaking",
    category: "Home Basics",
    title: "Air Conditioner Is Leaking",
    summary: "What to check safely before contacting management about AC water leakage.",
    keywords: ["air conditioner", "AC", "leaking", "water", "appliance"],
    riskLevel: "Medium",
    risk: "Medium",
    time: "10 min",
    diy: "Observe only",
    beforeYouStart: ["Turn the air conditioner off.", "Move electronics and bedding away from dripping water.", "Do not open the unit body."],
    tools: ["Towels", "Bucket", "Phone camera"],
    problem: "Water is dripping from the air conditioner or wall area.",
    steps: ["Turn off the unit and place a towel or bucket under the drip.", "Take photos of the leak, remote settings, and wall area.", "Check only the removable filter if the manual says it is safe.", "Send photos to building management or the landlord."],
    stopAndAskForHelp: "Stop and contact your landlord, building management, utility company, or emergency service if water is near an outlet, the unit smells burnt, sparks, makes unusual sounds, or leakage is heavy.",
    warning: "Stop and contact your landlord, building management, utility company, or emergency service if water is near an outlet, the unit smells burnt, sparks, makes unusual sounds, or leakage is heavy.",
    japanesePhrases: ["エアコンから水が漏れています。", "写真を送ります。", "修理業者の手配をお願いします。"],
    phrases: ["エアコンから水が漏れています。", "写真を送ります。", "修理業者の手配をお願いします。"],
  },
  {
    id: "first-hospital-visit",
    category: "Food & Health",
    title: "First Hospital Visit",
    summary: "A practical guide for choosing a clinic, preparing documents, and explaining symptoms.",
    keywords: ["hospital", "clinic", "health", "insurance", "doctor"],
    riskLevel: "Low",
    risk: "Low",
    time: "25 min",
    diy: "Yes",
    beforeYouStart: ["If symptoms are severe, call emergency services instead of waiting.", "Check whether the clinic accepts your insurance.", "Prepare a short symptom note."],
    tools: ["Health insurance card", "Residence card", "Medication list", "Cash or card"],
    problem: "You need medical help but are unsure how to visit a clinic alone.",
    steps: ["Search for a clinic matching your symptom and language needs.", "Call or check online whether reservations are required.", "Write when symptoms started, pain level, allergies, and current medication.", "Ask the reception what to do next after the visit."],
    stopAndAskForHelp: "Call emergency services for chest pain, trouble breathing, heavy bleeding, loss of consciousness, severe allergic reaction, or any situation that feels urgent.",
    warning: "Call emergency services for chest pain, trouble breathing, heavy bleeding, loss of consciousness, severe allergic reaction, or any situation that feels urgent.",
    japanesePhrases: ["初診です。", "保険証を持っています。", "症状はいつからですか？"],
    phrases: ["初診です。", "保険証を持っています。", "症状はいつからですか？"],
  },
  {
    id: "garbage-sorting",
    category: "Cleaning",
    title: "Garbage Sorting Basics",
    summary: "A first-pass routine for sorting burnable, plastic, bottles, cans, and oversized trash.",
    keywords: ["garbage", "trash", "cleaning", "sorting", "recycling"],
    risk: "Low",
    riskLevel: "Low",
    time: "20 min",
    diy: "Yes",
    beforeYouStart: ["Check your ward or city garbage calendar.", "Do not leave personal documents visible in trash.", "Rinse containers before storing them."],
    tools: ["City garbage calendar", "Transparent bags", "Marker", "Small bins"],
    problem: "You need a simple system for sorting trash without letting it pile up.",
    steps: ["Separate burnable trash, plastics, bottles, cans, and paper.", "Write collection days on a visible note near the door.", "Rinse bottles and cans before storing them.", "Book oversized trash collection before moving or replacing furniture."],
    stopAndAskForHelp: "Ask building management or your city office if you are unsure about batteries, spray cans, sharp objects, or oversized garbage.",
    warning: "Ask building management or your city office if you are unsure about batteries, spray cans, sharp objects, or oversized garbage.",
    japanesePhrases: [],
    phrases: [],
  },
  {
    id: "moving-checklist",
    category: "Moving",
    title: "Moving Checklist",
    summary: "A calm moving sequence for utilities, keys, documents, first-night items, and safety checks.",
    keywords: ["moving", "move", "checklist", "rent", "first night"],
    risk: "Low",
    riskLevel: "Low",
    time: "45 min",
    diy: "Yes",
    beforeYouStart: ["Keep keys, contract papers, and ID in one bag.", "Pack one first-night kit before sealing boxes.", "Photograph the empty room before unpacking."],
    tools: ["First-night bag", "Chargers", "Trash bags", "Contract documents", "Phone camera"],
    problem: "Moving day can become overwhelming if essential items disappear into boxes.",
    steps: ["Schedule electricity, gas, water, and internet before moving day.", "Pack toiletries, towel, pajamas, medicine, chargers, and cash in one visible bag.", "Take photos of walls, floors, appliances, and existing damage.", "Set up light, bedding, water, and phone charging before decorating."],
    stopAndAskForHelp: "Contact building management if keys, locks, gas, electricity, water, or appliance setup seems unclear or unsafe.",
    warning: "Contact building management if keys, locks, gas, electricity, water, or appliance setup seems unclear or unsafe.",
    japanesePhrases: ["引っ越し当日に確認したいです。", "鍵を受け取りました。", "既存の傷を写真で残します。"],
    phrases: ["引っ越し当日に確認したいです。", "鍵を受け取りました。", "既存の傷を写真で残します。"],
  },
  {
    id: "lost-key",
    category: "Emergency",
    title: "Lost Your Key",
    summary: "What to do when you cannot enter your room without making the situation unsafe.",
    keywords: ["lost key", "key", "lock", "emergency", "landlord"],
    risk: "Medium",
    riskLevel: "Medium",
    time: "20 min",
    diy: "No forced entry",
    beforeYouStart: ["Move to a bright public place if it is late.", "Do not try to force the door open.", "Keep your phone charged and contacts visible."],
    tools: ["Phone", "ID", "Rental contract", "Emergency contact"],
    problem: "You lost your key or cannot enter your apartment.",
    steps: ["Check your bag, coat pockets, last cafe, station, and workplace once.", "Call building management, landlord, or the official lock support number.", "Confirm identity requirements and cost before agreeing to locksmith service.", "If you feel unsafe waiting outside, go to a convenience store, station, or trusted public place."],
    stopAndAskForHelp: "Contact building management, your landlord, or police if someone may have stolen your key, your address is identifiable, or you feel unsafe outside.",
    warning: "Contact building management, your landlord, or police if someone may have stolen your key, your address is identifiable, or you feel unsafe outside.",
    japanesePhrases: ["鍵をなくしました。", "部屋に入れません。", "身分証を持っています。"],
    phrases: ["鍵をなくしました。", "部屋に入れません。", "身分証を持っています。"],
  },
  {
    id: "gas-smell",
    category: "Emergency",
    title: "Smell Gas at Home",
    summary: "A high-risk guide for leaving safely and contacting the right service.",
    keywords: ["gas", "smell", "emergency", "utility", "fire"],
    riskLevel: "High",
    risk: "High",
    time: "Immediate",
    diy: "No",
    beforeYouStart: ["Do not use flames.", "Do not switch lights or appliances on or off.", "Open a window only if you can do it immediately and safely."],
    tools: ["Phone after leaving", "Building emergency contact"],
    problem: "You smell gas or suspect a gas leak.",
    steps: ["Stop using gas immediately.", "Leave the room and move away from the suspected leak.", "Call the gas company emergency number, building management, or emergency service from outside.", "Do not re-enter until professionals say it is safe."],
    stopAndAskForHelp: "Stop and contact your landlord, building management, utility company, or emergency service. Do not try to repair gas equipment yourself.",
    warning: "Stop and contact your landlord, building management, utility company, or emergency service. Do not try to repair gas equipment yourself.",
    japanesePhrases: ["ガスのにおいがします。", "ガス漏れの可能性があります。", "外に避難しました。"],
    phrases: ["ガスのにおいがします。", "ガス漏れの可能性があります。", "外に避難しました。"],
  },
  {
    id: "breaker-keeps-tripping",
    category: "Emergency",
    title: "Breaker Keeps Tripping",
    summary: "How to respond when electricity repeatedly cuts out without touching wiring.",
    keywords: ["electricity", "breaker", "power", "outage", "appliance fault"],
    riskLevel: "High",
    risk: "High",
    time: "Immediate",
    diy: "No wiring",
    beforeYouStart: ["Do not touch exposed wires.", "Unplug devices only if the outlet area is dry and safe.", "Keep away from burning smells or heat."],
    tools: ["Phone", "Flashlight", "Utility bill or provider name"],
    problem: "The breaker trips repeatedly, power cuts out, or an appliance may be unsafe.",
    steps: ["Turn off and unplug the appliance you were using if safe.", "Move away from outlets, sparks, heat, or burning smell.", "Take note of which room or device was involved.", "Contact building management or the electricity provider."],
    stopAndAskForHelp: "Stop and contact your landlord, building management, utility company, or emergency service. Do not open electrical panels, repair wiring, or keep using a dangerous appliance.",
    warning: "Stop and contact your landlord, building management, utility company, or emergency service. Do not open electrical panels, repair wiring, or keep using a dangerous appliance.",
    japanesePhrases: ["ブレーカーが何度も落ちます。", "焦げたにおいがします。", "電気会社に連絡したいです。"],
    phrases: ["ブレーカーが何度も落ちます。", "焦げたにおいがします。", "電気会社に連絡したいです。"],
  },
  {
    id: "rent-contract-basics",
    category: "Money & Budget",
    title: "Rent Contract Basics",
    summary: "A quick guide to fees, renewal terms, guarantors, and questions to ask before signing.",
    keywords: ["rent", "contract", "apartment", "budget", "guarantor"],
    riskLevel: "Low",
    risk: "Low",
    time: "25 min",
    diy: "Yes",
    beforeYouStart: ["Read fees slowly.", "Ask for written explanations.", "Do not sign under pressure."],
    tools: ["Contract draft", "Fee list", "Translation app", "Notebook"],
    problem: "You want to understand the money and obligations before signing a rental contract.",
    steps: ["List rent, management fee, deposit, key money, insurance, guarantor fee, and renewal fee.", "Check cancellation rules, repair responsibilities, and guest or noise rules.", "Ask what happens if you lose a key or need emergency repair.", "Take time to compare the contract with your monthly budget."],
    stopAndAskForHelp: "Ask a trusted person, school office, workplace support, or housing consultation service if fees are unclear or you feel pressured.",
    warning: "Ask a trusted person, school office, workplace support, or housing consultation service if fees are unclear or you feel pressured.",
    japanesePhrases: ["契約内容を確認したいです。", "この費用は何ですか？", "少し考える時間をください。"],
    phrases: ["契約内容を確認したいです。", "この費用は何ですか？", "少し考える時間をください。"],
  },
];

export const places = [
  {
    id: "mori-cafe",
    name: "Mori Window Cafe",
    category: "Cafe",
    area: "Kichijoji",
    distance: "0.4 km",
    distanceFrom: "Kichijoji Station",
    description: "A soft, solo-friendly cafe with window seats, warm light, and an easy stay-alone rhythm.",
    openingHours: "08:00-20:30",
    priceRange: "1000-1800 yen",
    experienceTags: ["First solo visit", "Calm and slow", "Good for reading", "Work-friendly"],
    practicalTags: ["Solo-friendly", "Window seats", "Clean restroom", "Kind staff"],
    whyRecommended: [
      "Small tables and window seats make staying alone feel natural.",
      "Staff are used to customers reading or working quietly.",
      "The entrance faces a bright shopping street during daytime hours.",
    ],
    image: "place-mori-window-cafe.png",
    // mapPosition is for the internal editorial prototype map; lat/lng are only for external Google Maps links.
    mapPosition: { x: 34, y: 38 },
    lat: 35.7031,
    lng: 139.5792,
    prototypeData: true,
    budget: "1000-1800 yen",
    open: true,
    safe: 94,
    solo: 96,
    women: 95,
    address: "Prototype address, Kichijoji",
    hours: "08:00-20:30",
    reason: "Small tables and window seats make staying alone feel natural.",
    womenFriendly: "Well-lit entrance, clean restroom, no pressure to order quickly, and staff check on late guests.",
    soloReason: "Small tables, counter seats, quiet reading mood, and outlets near the wall.",
    review: "I stayed for an hour with a book and felt completely unhurried.",
  },
  {
    id: "haru-fast-table",
    name: "Haru Fast Table",
    category: "Restaurant",
    area: "Shinjuku",
    distance: "0.2 km",
    distanceFrom: "Shinjuku Station",
    description: "A fictional fast food spot designed for affordable solo meals near a station exit.",
    openingHours: "07:00-23:00",
    priceRange: "700-1200 yen",
    experienceTags: ["Eating alone", "Women-friendly", "Low budget", "First solo visit"],
    practicalTags: ["Counter seats", "Near station", "Affordable", "Quick order"],
    whyRecommended: [
      "Counter seats make solo dining feel expected instead of awkward.",
      "The entrance is visible from the station-side street.",
      "Affordable set meals make it easy to try without committing to a long dinner.",
    ],
    image: "place-yuzu-solo-table.png",
    mapPosition: { x: 32, y: 42 },
    lat: 35.6907,
    lng: 139.7004,
    prototypeData: true,
    budget: "700-1200 yen",
    open: true,
    safe: 90,
    solo: 98,
    women: 91,
    address: "Prototype address, Shinjuku",
    hours: "07:00-23:00",
    reason: "Counter seats make solo dining feel expected instead of awkward.",
    womenFriendly: "This prototype place is modeled around clear seating, visible staff, and a bright entrance.",
    soloReason: "Fast counter ordering and one-person seats reduce the pressure of eating alone.",
    review: "A practical first solo dinner option.",
  },
  {
    id: "tsuki-books",
    name: "Tsuki Books",
    category: "Bookstore",
    area: "Shimokitazawa",
    distance: "0.5 km",
    distanceFrom: "Shimokitazawa Station",
    description: "A quiet bookstore with essays, zines, and a small reading bench near the front desk.",
    openingHours: "11:00-21:00",
    priceRange: "0-2500 yen",
    experienceTags: ["Calm and slow", "Good for reading", "First solo visit"],
    practicalTags: ["Quiet browsing", "Visible staff", "Small seating nook"],
    whyRecommended: [
      "Browsing alone feels natural because the store is set up for slow discovery.",
      "The staff desk faces the entrance, so the layout feels easy to understand.",
      "A small seating nook gives you a place to pause before choosing a book.",
    ],
    image: "place-tsuki-books.png",
    mapPosition: { x: 39, y: 40 },
    lat: 35.6618,
    lng: 139.6672,
    prototypeData: true,
    budget: "0-2500 yen",
    open: true,
    safe: 91,
    solo: 98,
    women: 92,
    address: "Prototype address, Shimokitazawa",
    hours: "11:00-21:00",
    reason: "Browsing alone feels natural because the store is set up for slow discovery.",
    womenFriendly: "Staff desk faces the entrance and the shop is on a bright street.",
    soloReason: "Browsing alone feels natural, with zines, essays, and small gift shelves.",
    review: "A good place to reset before going home.",
  },
  {
    id: "hana-room",
    name: "Hana Room",
    category: "Flower Shop",
    area: "Ueno",
    distance: "0.3 km",
    distanceFrom: "Ueno Station",
    description: "A fictional women-owned flower shop for small bouquets, single stems, and gentle first visits.",
    openingHours: "10:00-19:00",
    priceRange: "600-2000 yen",
    experienceTags: ["Women-friendly", "First solo visit", "Calm and slow"],
    practicalTags: ["Women-owned", "Small bouquets", "Budget friendly", "Street-facing counter"],
    whyRecommended: [
      "Buying one stem is welcomed, so the visit can stay small and low pressure.",
      "The street-facing counter makes it easy to enter, ask, and leave at your pace.",
      "Staff can suggest a small bouquet within a clear budget.",
    ],
    image: "place-hana-room.png",
    mapPosition: { x: 34, y: 44 },
    lat: 35.7137,
    lng: 139.7733,
    prototypeData: true,
    budget: "600-2000 yen",
    open: true,
    safe: 89,
    solo: 90,
    women: 96,
    address: "Prototype address, Ueno",
    hours: "10:00-19:00",
    reason: "Buying one stem is welcomed, so the visit can stay small and low pressure.",
    womenFriendly: "Staff are used to solo customers and can make small budget bouquets.",
    soloReason: "A quick, gentle stop that makes a room feel cared for.",
    review: "I bought one flower after a hard day and it changed the whole room.",
  },
  {
    id: "luna-boxing-studio",
    name: "Luna Boxing Studio",
    category: "Gym",
    area: "Shinjuku",
    distance: "0.7 km",
    distanceFrom: "Shinjuku Station",
    description: "A fictional women-friendly boxing studio focused on trial lessons and complete beginners.",
    openingHours: "07:00-22:00",
    priceRange: "1800 yen trial",
    experienceTags: ["Beginner-friendly", "Women-friendly", "Try something new"],
    practicalTags: ["Trial available", "Friendly instructors", "Many beginners", "Female members"],
    whyRecommended: [
      "Many first-time members join the trial lesson, so arriving alone is part of the flow.",
      "Instructors explain wraps, gloves, and class order before the session starts.",
      "The reception area is visible and the schedule clearly marks beginner classes.",
    ],
    image: "place-luna-boxing-studio.png",
    mapPosition: { x: 58, y: 34 },
    lat: 35.6922,
    lng: 139.7041,
    prototypeData: true,
    budget: "1800 yen trial",
    open: true,
    safe: 90,
    solo: 88,
    women: 94,
    address: "Prototype address, Shinjuku",
    hours: "07:00-22:00",
    reason: "Many first-time members join the trial lesson, so arriving alone is part of the flow.",
    womenFriendly: "This prototype place is modeled around clear class flow and beginner support.",
    soloReason: "Trial lessons make it easy to arrive alone and leave at your own pace.",
    review: "A good first step for trying a strong new habit.",
  },
  {
    id: "nagi-museum",
    name: "Nagi Museum Hour",
    category: "Museum",
    area: "Ueno",
    distance: "1.2 km",
    distanceFrom: "Ueno Station",
    description: "A compact museum route for moving slowly, using lockers, and visiting without a group.",
    openingHours: "09:30-17:30",
    priceRange: "1200 yen",
    experienceTags: ["First solo visit", "Calm and slow", "Try something new"],
    practicalTags: ["Lockers", "Visible attendants", "Clear route"],
    whyRecommended: [
      "The route is simple enough to enjoy without planning a full museum day.",
      "Lockers help you move freely when visiting alone.",
      "No one expects you to talk, hurry, or explain your pace.",
    ],
    image: "place-nagi-museum.png",
    mapPosition: { x: 58, y: 36 },
    lat: 35.7188,
    lng: 139.7765,
    prototypeData: true,
    budget: "1200 yen",
    open: false,
    safe: 93,
    solo: 97,
    women: 91,
    address: "Prototype address, Ueno",
    hours: "09:30-17:30",
    reason: "No one expects you to talk, hurry, or explain your pace.",
    womenFriendly: "Visible attendants and safe restroom access throughout the building.",
    soloReason: "Good for moving slowly without explaining your pace to anyone.",
    review: "Perfect for an inspiration day.",
  },
  {
    id: "riverside-park",
    name: "Riverside Park",
    category: "Park",
    area: "Kichijoji",
    distance: "0.8 km",
    distanceFrom: "Kichijoji Station",
    description: "A fictional daytime park edge with open sightlines, benches, and exits toward busy streets.",
    openingHours: "05:00-23:00",
    priceRange: "0 yen",
    experienceTags: ["Calm and slow", "Low budget", "First solo visit"],
    practicalTags: ["Open sightlines", "Daytime walk", "Benches", "Nearby cafes"],
    whyRecommended: [
      "Open sightlines make it easier to choose where to sit or walk.",
      "Several exits point back toward shops and cafes.",
      "It works well as a short reset instead of a long isolated walk.",
    ],
    image: "place-riverside-park.png",
    mapPosition: { x: 58, y: 62 },
    lat: 35.7002,
    lng: 139.5739,
    prototypeData: true,
    budget: "0 yen",
    open: true,
    safe: 88,
    solo: 94,
    women: 89,
    address: "Prototype address, Kichijoji",
    hours: "05:00-23:00",
    reason: "Open sightlines make it easier to choose where to sit or walk.",
    womenFriendly: "Good daytime visibility and many nearby cafes for a quick safe stop.",
    soloReason: "Easy to sit, sketch, read, or walk without feeling watched.",
    review: "A soft reset place before going back home.",
  },
  {
    id: "station-late-cafe",
    name: "Station Glow Cafe",
    category: "Cafe",
    area: "Shinjuku",
    distance: "0.1 km",
    distanceFrom: "Shinjuku Station",
    description: "A fictional night-friendly cafe beside a staffed station exit for a bright final stop.",
    openingHours: "10:00-23:30",
    priceRange: "900-1800 yen",
    experienceTags: ["Night-friendly", "Eating alone", "Work-friendly"],
    practicalTags: ["Near station", "Bright entrance", "Counter seats", "Staffed street"],
    whyRecommended: [
      "The entrance is visible from the station exit.",
      "Counter seats make a short solo dinner or drink feel natural.",
      "It can be used as a bright waiting point before heading home.",
    ],
    image: "place-station-glow-cafe.png",
    mapPosition: { x: 45, y: 58 },
    lat: 35.6901,
    lng: 139.7016,
    prototypeData: true,
    budget: "900-1800 yen",
    open: true,
    safe: 89,
    solo: 95,
    women: 90,
    address: "Prototype address, Shinjuku",
    hours: "10:00-23:30",
    reason: "The entrance is visible from the station exit.",
    womenFriendly: "This prototype place is modeled around bright frontage and clear staff presence.",
    soloReason: "Counter seats make a short solo dinner or drink feel natural.",
    review: "A useful last stop before the train home.",
  },
  {
    id: "clay-nest-studio",
    name: "Clay Nest Studio",
    category: "Activity",
    area: "Shimokitazawa",
    distance: "0.6 km",
    distanceFrom: "Shimokitazawa Station",
    description: "A fictional beginner pottery class where first-timers can make one small cup alone.",
    openingHours: "11:00-20:00",
    priceRange: "3000-5000 yen",
    experienceTags: ["Beginner-friendly", "Try something new", "First solo visit"],
    practicalTags: ["Trial available", "Small class", "Instructor demo", "Take-home piece"],
    whyRecommended: [
      "The class starts with a demonstration, so beginners do not need prior knowledge.",
      "Small groups make it normal to attend alone.",
      "The project is limited to one piece, keeping the experience manageable.",
    ],
    image: "place-clay-nest-studio.png",
    mapPosition: { x: 60, y: 34 },
    lat: 35.6624,
    lng: 139.6685,
    prototypeData: true,
    budget: "3000-5000 yen",
    open: true,
    safe: 88,
    solo: 90,
    women: 89,
    address: "Prototype address, Shimokitazawa",
    hours: "11:00-20:00",
    reason: "Small groups make it normal to attend alone.",
    womenFriendly: "This prototype class is modeled around beginner support and visible instructor guidance.",
    soloReason: "The single-piece project keeps the experience manageable.",
    review: "A gentle way to try something with your hands.",
  },
  {
    id: "yuzu-table",
    name: "Yuzu Solo Table",
    category: "Restaurant",
    area: "Shimokitazawa",
    distance: "0.5 km",
    distanceFrom: "Shimokitazawa Station",
    description: "A fictional restaurant with intentional one-person counter seats and calm dinner pacing.",
    openingHours: "11:30-22:00",
    priceRange: "1200-2600 yen",
    experienceTags: ["Eating alone", "Calm and slow", "First solo visit"],
    practicalTags: ["Counter seats", "Solo-friendly", "Clear menu", "Lively street"],
    whyRecommended: [
      "Single seats are intentional, not an afterthought.",
      "Staff ask seating preference before guiding customers.",
      "The menu is simple enough for a first solo dinner.",
    ],
    image: "place-yuzu-solo-table.png",
    mapPosition: { x: 53, y: 62 },
    lat: 35.6612,
    lng: 139.6668,
    prototypeData: true,
    budget: "1200-2600 yen",
    open: true,
    safe: 87,
    solo: 99,
    women: 90,
    address: "Prototype address, Shimokitazawa",
    hours: "11:30-22:00",
    reason: "Single seats are intentional, not an afterthought.",
    womenFriendly: "Staff check seating preference and the entrance faces a lively street.",
    soloReason: "Single seats are intentional, not an afterthought.",
    review: "Dinner alone felt normal here.",
  },
  {
    id: "green-kitchen-class",
    name: "Green Kitchen Class",
    category: "Activity",
    area: "Ueno",
    distance: "0.9 km",
    distanceFrom: "Ueno Station",
    description: "A fictional beginner cooking class with a simple menu and clear prep stations.",
    openingHours: "10:00-20:00",
    priceRange: "3500 yen",
    experienceTags: ["Beginner-friendly", "Try something new", "Women-friendly"],
    practicalTags: ["Small class", "Recipe card", "Instructor demo", "Beginner tools"],
    whyRecommended: [
      "The recipe is short and prepared in clear stages.",
      "Instructor demos reduce the pressure of knowing what to do first.",
      "The class format gives you something to focus on when attending alone.",
    ],
    image: "place-green-kitchen-class.png",
    mapPosition: { x: 45, y: 64 },
    lat: 35.7119,
    lng: 139.7752,
    prototypeData: true,
    budget: "3500 yen",
    open: true,
    safe: 89,
    solo: 88,
    women: 91,
    address: "Prototype address, Ueno",
    hours: "10:00-20:00",
    reason: "The class format gives you something to focus on when attending alone.",
    womenFriendly: "This prototype class is modeled around clear instruction and beginner tools.",
    soloReason: "A structured activity gives solo visitors a natural role.",
    review: "Good for trying something new without needing a friend to join.",
  },
  {
    id: "sora-work-lounge",
    name: "Sora Work Lounge",
    category: "Cafe",
    area: "Kichijoji",
    distance: "0.6 km",
    distanceFrom: "Kichijoji Station",
    description: "A fictional quiet work cafe with outlets, individual seats, and a no-rush afternoon mood.",
    openingHours: "09:00-21:00",
    priceRange: "1200-2200 yen",
    experienceTags: ["Work-friendly", "Good for reading", "Calm and slow"],
    practicalTags: ["Outlets", "Individual seats", "Quiet tables", "Clean restroom"],
    whyRecommended: [
      "Individual seats make it easy to bring a laptop or book alone.",
      "Staff are used to customers staying for a focused work block.",
      "The room is quiet without feeling isolated.",
    ],
    image: "place-sora-work-lounge.png",
    mapPosition: { x: 47, y: 55 },
    lat: 35.7042,
    lng: 139.5777,
    prototypeData: true,
    budget: "1200-2200 yen",
    open: true,
    safe: 91,
    solo: 96,
    women: 90,
    address: "Prototype address, Kichijoji",
    hours: "09:00-21:00",
    reason: "Individual seats make it easy to bring a laptop or book alone.",
    womenFriendly: "This prototype place is modeled around clear seating and quiet staff presence.",
    soloReason: "The layout supports long solo reading or work blocks.",
    review: "An easy place to finish a personal project.",
  },
];

export const dayRules = {
  Peace: ["Cafe", "Bookstore", "Flower Shop", "Park"],
  Explore: ["Museum", "Vintage Store", "Cafe", "Bookstore"],
  Inspiration: ["Museum", "Bookstore", "Flower Shop", "Cafe"],
  "Self-care": ["Gym", "Clinic", "Healthy Cafe", "Park"],
  "Romanticize life": ["Flower Shop", "Cafe", "Park", "Solo Restaurant"],
  "Night walk": ["Cafe", "Bookstore", "Convenience Store", "Night Walk Spot"],
};

export const daySuggestions = [
  {
    id: "gentle-kichijoji-reset",
    title: "Gentle Kichijoji Reset",
    mood: "Peace",
    area: "Kichijoji",
    duration: "Half day",
    budget: "3000 yen",
    description: "A slow afternoon for coffee, air, and a safe walk back toward the station.",
    includes: ["Cafe", "Park", "Night Walk Spot"],
    routePlaceholder: "Route placeholder: Mori Window Cafe → Riverside Park → Lantern Walk Street.",
    stops: [
      {
        time: "11:00",
        title: "Mori Window Cafe",
        type: "Cafe",
        placeId: "mori-cafe",
        description: "Start with a window seat, warm drink, and a quiet reset.",
      },
      {
        time: "13:00",
        title: "Riverside Park",
        type: "Park",
        placeId: "riverside-park",
        description: "Take a visible daytime walk with open exits and nearby cafes.",
      },
      {
        time: "15:00",
        title: "Lantern Walk Street",
        type: "Night Walk Spot",
        description: "Check the brighter route you can reuse on a late evening.",
      },
    ],
  },
  {
    id: "bookish-shimokitazawa",
    title: "Bookish Solo Afternoon",
    mood: "Inspiration",
    area: "Shimokitazawa",
    duration: "2h",
    budget: "3000 yen",
    description: "A compact solo plan for browsing, noticing small details, and eating without rushing.",
    includes: ["Bookstore", "Flower Shop", "Solo Restaurant"],
    routePlaceholder: "Route placeholder: Tsuki Books → small flower stop → Yuzu Solo Table.",
    stops: [
      {
        time: "13:00",
        title: "Tsuki Books",
        type: "Bookstore",
        placeId: "tsuki-books",
        description: "Browse essays, zines, and a shelf that feels like it found you first.",
      },
      {
        time: "14:00",
        title: "Small flower stop",
        type: "Flower Shop",
        description: "Choose one stem for your room instead of a full bouquet.",
      },
      {
        time: "15:00",
        title: "Yuzu Solo Table",
        type: "Solo Restaurant",
        placeId: "yuzu-table",
        description: "End with an easy counter seat made for one-person dinners.",
      },
    ],
  },
  {
    id: "ueno-soft-inspiration",
    title: "Ueno Soft Inspiration",
    mood: "Explore",
    area: "Ueno",
    duration: "Half day",
    budget: "5000 yen",
    description: "A museum-led day with flowers and a quiet pause before heading home.",
    includes: ["Museum", "Flower Shop", "Cafe"],
    routePlaceholder: "Route placeholder: Nagi Museum Hour → Hana Room → quiet cafe break.",
    stops: [
      {
        time: "10:30",
        title: "Nagi Museum Hour",
        type: "Museum",
        placeId: "nagi-museum",
        description: "Move slowly through one exhibition without needing to explain your pace.",
      },
      {
        time: "13:00",
        title: "Hana Room",
        type: "Flower Shop",
        placeId: "hana-room",
        description: "Pick a small bouquet with a clear budget and kind staff guidance.",
      },
      {
        time: "15:00",
        title: "Quiet cafe break",
        type: "Cafe",
        description: "Write down one thing you want to bring back into your room.",
      },
    ],
  },
  {
    id: "shinjuku-self-care-evening",
    title: "Self-care Evening",
    mood: "Self-care",
    area: "Shinjuku",
    duration: "2h",
    budget: "5000 yen",
    description: "A practical evening for moving your body, eating well, and leaving by a bright route.",
    includes: ["Gym", "Healthy Cafe", "Safe Route"],
    routePlaceholder: "Route placeholder: Luna Studio Gym → healthy cafe → staffed station exit.",
    stops: [
      {
        time: "18:00",
        title: "Luna Studio Gym",
        type: "Gym",
        placeId: "luna-boxing-studio",
        description: "Choose a beginner-friendly class with clear staff support.",
      },
      {
        time: "19:15",
        title: "Healthy cafe dinner",
        type: "Healthy Cafe",
        description: "Eat somewhere bright, simple, and comfortable for arriving alone.",
      },
      {
        time: "20:15",
        title: "Staffed station exit",
        type: "Safe Route",
        description: "Start the route home from a staffed, well-lit entrance.",
      },
    ],
  },
];

export const areas = ["Shinjuku", "Kichijoji", "Ueno", "Shimokitazawa"];
export const times = ["2h", "Half day", "Full day"];
export const budgets = ["1000 yen", "3000 yen", "5000 yen"];
export const moods = Object.keys(dayRules);
export const livingCategories = ["Home Basics", "Money & Budget", "Food & Health", "Cleaning", "Moving", "Emergency"];
export const placeExperienceFilters = [
  "First solo visit",
  "Women-friendly",
  "Beginner-friendly",
  "Eating alone",
  "Try something new",
  "Calm and slow",
  "Good for reading",
  "Work-friendly",
  "Night-friendly",
  "Low budget",
];
export const placeCategories = ["All", "Cafe", "Restaurant", "Bookstore", "Flower Shop", "Gym", "Activity", "Park", "Museum"];
export const categoryMap = {
  All: "All",
};
export const categoryIcons = {
  All: "⌂",
  Cafe: "☕",
  Restaurant: "▱",
  Bookstore: "▤",
  "Flower Shop": "✿",
  Gym: "∞",
  Activity: "✦",
  Park: "♧",
  Museum: "□",
};

export const favoritePlaceIds = ["mori-cafe", "hana-room"];

export const savedDayPlans = [
  {
    id: "day-1",
    title: "Soft Kichijoji afternoon",
    mood: "Peace",
    area: "Kichijoji",
    stops: ["11:00 Cafe", "13:00 Bookstore", "15:00 Flower Shop", "16:00 Park"],
  },
];
